### ISSUE TITLE
Overlaps in layout

### ISSUE THREAD

**Issue by AntonPetrov** [fjossinet/RNArtistCore#3]
👋 Hi Fabrice @fjossinet!

Hope you are well! I was playing around with RNArtistCore using Docker and `amazoncoretto`, and I really appreciate the DSL now! This is a super cool way of looking at RNA structure.

I was trying to draw some structures and ran into this layout: 

![stockholm](https://github.com/fjossinet/RNArtistCore/assets/432675/fb1264f6-a440-410f-8f55-1f30a26ee043)

Is there a way to avoid the overlap? Or is it because I am using a release from a while ago and it's all fine in the latest version?

This is my command:

`java -jar /rna/rnartistcore-0.3.8-SNAPSHOT-jar-with-dependencies.jar --with-svg -f /rna/root_folder/rna1/rna.kts`

Here is `rna.kts`:

```
rnartist {
  png {
    path = "media/"
  }

  svg {
    path = "media/"
  }

  ss {
    stockholm {
      file = "/rna/root_folder/rna1/stockholm.sto"
    }
  }

  theme {
    details {
      value = 2
    }
  }
}
```

And here is the Stockholm file:

```text
# STOCKHOLM 1.0

#=GF DE test
#=GF TP test

test_rna  NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
#=GC SS_cons   (((..(((((..((..(((.......)))..)).((((......)))).(((((....)))))(((((....)))))(((...(((((......))).)).)))..))))).))).
//
```

Any help will be greatly appreciated! Thanks a lot for creating this wonderful tool.

**Comment by fjossinet** [comment]
Hi Anton,

Cool that you like the DSL! 

There was a glitch concerning the location of the neighbouring helices inside a junction.  I have updated RNArtistCore right now. If you use the last release [RNArtistCore 0.4.4-SNAPSHOT](https://github.com/fjossinet/RNArtistCore/releases/tag/0.4.4-SNAPSHOT) you will get this result for your 2D:

![stockholm](https://github.com/fjossinet/RNArtistCore/assets/389452/fcb791d1-f1ae-422c-9605-9be61c885dcf)

The layout has been improved and the junctions are now curved to get a better rendering. 

This overlap between neighbouring helices still exist if:

- the size of the junction is small (the size of a junction is computed according to the number of helices connected to it)
- AND the algorithm needs to locate all the helices too close to each other to produce a global non-overlapped layout. 

At now, the logic behind the algorithm cannot predict the location of the helices before to compute the size of the junction.

**Comment by AntonPetrov** [comment]
Hi Fabrice!

Thank you for looking into this so quickly! There must have been some change in the command line behaviour since the last release because now when I run the same command in the same environment, it says:

```
java -jar /rna/rnartistcore-0.4.4-SNAPSHOT-jar-with-dependencies.jar --with-svg -f /rna/root_folder/rna1/rna.kts
The script rna.kts.kts already exists. Do you agree to overwrite it? [y/N]
```

and if I say `N` it does not do anything and if I say `y` it creates a new file:

```
import io.github.fjossinet.rnartist.core.*

 rnartist {
   
    theme {
       details {
          value = 4
          step = 1
       }
       scheme {
          value = "Midnight Paradise"
          step = 1
       }
       line {
          value = 2.5
          step = 1
       }
    }
 }
```

I must be missing something but what is the preferred way of invoking `rnartistcore-XXX.jar` to process just one structure?

Thank you!

**Comment by fjossinet** [comment]
Hi Anton,

Nothing has changed but I did not see that you used the option -f to launch a script in your first message. This option is needed if you have a structural file and no script. RNArtistCore will generate a default script for you. You can also remove the option --with-svg since this is also an option to be used if you don't have any script at first. Then RNArtistCore will add the svg output instruction to the default script. 

If you already have a script, meaning that everything is defined in it, just type:

`java -jar /rna/rnartistcore-0.4.4-SNAPSHOT-jar-with-dependencies.jar  /rna/root_folder/rna1/rna.kts`

I will add a check and warning to the command line tool if the option -f is used to launch a script. I could check the suffix of the file, but no guarantees that a user will use the right suffix (like .txt for Vienna files).

Hope this help.

**Comment by AntonPetrov** [comment]
Hooray! It worked and I got a beautiful diagram without overlaps! Thanks a lot, Fabrice! ⭐

I will close this issue and play with the software a bit more. Thanks again!
