### ISSUE TITLE
DE and TP fields should not be required in Stockholm format

### ISSUE THREAD

**Issue by AntonPetrov** [fjossinet/RNArtistCore#4]
Hi Fabrice!

Related to #3, I noticed that RNArtist refused to accept Stockholm files until I included the following lines:

```
#=GF DE test
#=GF TP test
```

These are required in Rfam Stockholm files but perhaps it is too strict to ask for any Stockholm file to have these? 

I figured it out by starting with an Rfam alignment and then removing `#=GF` lines until RNArtist was happy, but it could prevent other users from taking advantage of this amazing tool, so I thought I'd let you know.

Thanks a lot!

**Comment by fjossinet** [comment]
Good to know! I did not check by Stockholm parser since a while. You're right, I'm gonna remove this unnecessary limitation. I let u know when it's done. Thanks!

**Comment by fjossinet** [comment]
Hi Anton,

I have released RNArtistCore 0.4.5-SNAPSHOT. This issue should be fixed. Let me know.

**Comment by AntonPetrov** [comment]
It worked! 🎉

Thank you Fabrice!
