### ISSUE TITLE
Hiding residue numbers, basepair and backbone lines

### ISSUE THREAD

**Issue by AntonPetrov** [fjossinet/RNArtistCore#6]
Hi Fabrice!

I was reading the documentation but unfortunately I could not figure out how to show only the circles representing the nucleotides, without the residue numbers and small circles, basepair lines, and backbone lines (examples shown in red):

![rfline](https://github.com/fjossinet/RNArtistCore/assets/432675/60ac7510-71a6-48e3-8662-0642a77d87a6)

Your DSL is very powerful and I figured that there must be a way to do it, I just could not find it. 

Your help will be greatly appreciated! Many thanks again for your advice as I've got most elements in place now to use RNArtist for R2DT templates.

**Comment by fjossinet** [comment]
Concerning the numbering I can easily add it to the DSL syntax. For the symbols of the secondary interactions, you cannot remove them using the keyword ```hide``` (meaning render them lowly). They can be rendered either highly (LW symbols) or lowly (single lines as in your plot). But you can set the line width to 0.0 if this helps:

```kotlin
theme {
  details {
    value = 3
  }
  
  line {
    type = "interaction_symbol"
    value = 0.0
  }
}
```

Concerning the backbone lines, to you want to remove all of them, only those in helices, junctions...?

**Comment by AntonPetrov** [comment]
This works well, thank you!
```
  line {
    type = "interaction_symbol"
    value = 0.0
  }
```

>Concerning the backbone lines, to you want to remove all of them, only those in helices, junctions...?

To convert SVGs into R2DT templates I need to locate all residues and generate a [traveler](https://github.com/cusbg/traveler/)-format file like this:

```
<structure>
<point x="19.66" y="150.67" b="A"/>
<point x="27.02" y="150.67" b="U"/>
<point x="34.73" y="150.88" b="N"/>
<point x="42.28" y="150.88" b="N"/>
<point x="49.90" y="150.67" b="Y"/>
...
</structure>
```

However, over time I ran into lots of issues when parsing SVGs as sometimes an upstream algorithm can unexpectedly add new elements or change something, which is why I was asking how to remove unneeded elements completely to minimise the risk down the line.

However, I am not sure what is the best way forward here: asking for changes in the DSL to facilitate parsing, or, perhaps, if this is not too much, would you be able to generate a XML output file like that with an extra flag? That would be really helpful, but please feel free to push back on both of these requests, as the SVG is not too bad to parse in its current form.

**Comment by fjossinet** [comment]
No problem for me to add a new DSL keyword to produce a traveler output. So something like:

```kotlin
rnartist {

 traveler {
  path = "media/"
 }

 ss {
  stockholm {
   file = "/Volumes/T7/tmp/rfline.sto"
  }
 }

}
```

and this will produce a traveler XML file in the folder media and named rfline.traveler?

**Comment by AntonPetrov** [comment]
This would be amazing, thank you very much for offering to make such a file! 

Here is a complete example just in case it's useful:
https://github.com/RNAcentral/R2DT/blob/main/data/rfam/RF00003/traveler-template.xml

Many thanks again! 🤩

**Comment by fjossinet** [comment]
Hi Anton,

Could you test this sample before a commit? 

For this 2D:

![rfline_rf_line](https://github.com/fjossinet/RNArtistCore/assets/389452/f96a99f3-3da9-4bb4-bcb9-e7bdb8b87adf)


RNArtistCore produces this traveler data when the 2D plot is centered on a 1000x1000 area:

```xml
<structure>
<point x="193,71" y="880,67" b="A"/>
<point x="217,09" y="880,67" b="A"/>
<point x="240,47" y="880,67" b="A"/>
<point x="263,84" y="880,67" b="A"/>
<point x="287,22" y="880,67" b="A"/>
<point x="310,60" y="880,67" b="G"/>
<point x="310,60" y="847,27" b="C"/>
<point x="310,60" y="813,88" b="A"/>
<point x="310,60" y="780,48" b="U"/>
<point x="310,60" y="747,08" b="C"/>
<point x="298,11" y="742,08" b="A"/>
<point x="286,40" y="735,44" b="A"/>
<point x="275,69" y="727,30" b="G"/>
<point x="266,17" y="717,78" b="A"/>
<point x="258,03" y="707,07" b="G"/>
<point x="251,39" y="695,36" b="A"/>
<point x="246,39" y="682,87" b="G"/>
<point x="212,99" y="682,87" b="G"/>
<point x="179,59" y="682,87" b="G"/>
<point x="146,20" y="682,87" b="U"/>
<point x="112,80" y="682,87" b="C"/>
<point x="75,51" y="694,76" b="U"/>
<point x="43,91" y="671,68" b="A"/>
<point x="43,91" y="632,54" b="A"/>
<point x="75,51" y="609,45" b="A"/>
<point x="112,80" y="621,35" b="G"/>
<point x="146,20" y="621,35" b="A"/>
<point x="179,59" y="621,35" b="C"/>
<point x="212,99" y="621,35" b="C"/>
<point x="246,39" y="621,35" b="C"/>
<point x="270,77" y="581,52" b="C"/>
<point x="310,60" y="557,13" b="G"/>
<point x="310,60" y="523,74" b="C"/>
<point x="310,60" y="490,34" b="C"/>
<point x="292,44" y="464,85" b="A"/>
<point x="292,44" y="433,56" b="A"/>
<point x="310,60" y="408,08" b="C"/>
<point x="310,60" y="374,68" b="C"/>
<point x="310,60" y="341,28" b="U"/>
<point x="310,60" y="274,70" b="G"/>
<point x="310,60" y="241,30" b="G"/>
<point x="310,60" y="207,90" b="C"/>
<point x="293,20" y="178,92" b="U"/>
<point x="298,69" y="145,56" b="A"/>
<point x="324,46" y="123,68" b="A"/>
<point x="358,27" y="123,68" b="C"/>
<point x="384,04" y="145,56" b="C"/>
<point x="389,53" y="178,92" b="A"/>
<point x="372,12" y="207,90" b="G"/>
<point x="372,12" y="241,30" b="C"/>
<point x="372,12" y="274,70" b="C"/>
<point x="386,69" y="307,99" b="A"/>
<point x="372,12" y="341,28" b="A"/>
<point x="372,12" y="374,68" b="G"/>
<point x="372,12" y="408,08" b="G"/>
<point x="392,72" y="449,21" b="U"/>
<point x="372,12" y="490,34" b="G"/>
<point x="372,12" y="523,74" b="G"/>
<point x="372,12" y="557,13" b="C"/>
<point x="403,55" y="574,02" b="U"/>
<point x="427,04" y="600,87" b="A"/>
<point x="439,59" y="634,27" b="A"/>
<point x="439,59" y="669,95" b="A"/>
<point x="427,04" y="703,34" b="A"/>
<point x="403,55" y="730,20" b="A"/>
<point x="372,12" y="747,08" b="G"/>
<point x="372,12" y="780,48" b="A"/>
<point x="372,12" y="813,88" b="U"/>
<point x="372,12" y="847,27" b="G"/>
<point x="372,12" y="880,67" b="C"/>
<point x="440,94" y="880,67" b="G"/>
<point x="509,76" y="880,67" b="G"/>
<point x="509,76" y="847,27" b="C"/>
<point x="509,76" y="813,88" b="C"/>
<point x="509,76" y="780,48" b="C"/>
<point x="497,86" y="743,19" b="A"/>
<point x="520,95" y="711,59" b="A"/>
<point x="560,09" y="711,59" b="A"/>
<point x="583,17" y="743,19" b="A"/>
<point x="571,28" y="780,48" b="G"/>
<point x="571,28" y="813,88" b="G"/>
<point x="571,28" y="847,27" b="G"/>
<point x="571,28" y="880,67" b="C"/>
<point x="595,50" y="880,67" b="A"/>
<point x="619,73" y="880,67" b="A"/>
<point x="643,95" y="880,67" b="A"/>
<point x="668,18" y="880,67" b="A"/>
<point x="692,40" y="880,67" b="A"/>
<point x="716,62" y="880,67" b="A"/>
<point x="740,85" y="880,67" b="A"/>
<point x="765,07" y="880,67" b="G"/>
<point x="789,30" y="880,67" b="G"/>
<point x="813,52" y="880,67" b="A"/>
<point x="837,75" y="880,67" b="G"/>
<point x="861,97" y="880,67" b="U"/>
<point x="886,20" y="880,67" b="U"/>
<point x="910,42" y="880,67" b="A"/>
<point x="934,64" y="880,67" b="A"/>
<point x="958,87" y="880,67" b="A"/>
</structure>
```

**Comment by AntonPetrov** [comment]
Hi Fabrice! It worked! 🎉

I have 2 small requests:
- Could you please change the decimal separator to `.` instead of `,` so that `958,87` becomes `958.87`?
- Could you make the area smaller like 500x500 for consistency with existing R2DT templates? 

Here is an R2DT visualisation for one of the longer instances of RF01725 (URS0000D690D1_12908):

<img width="1286" alt="Screenshot 2023-12-20 at 12 04 25" src="https://github.com/fjossinet/RNArtistCore/assets/432675/4d48796b-bd95-4099-9c51-d275f9a0e839">

and here is a default R2DT image based on R2R:

<img width="837" alt="Screenshot 2023-12-20 at 12 04 45" src="https://github.com/fjossinet/RNArtistCore/assets/432675/919cab33-613e-492e-9729-d6d287b1a985">

In this case I prefer the RNArtist layout because it does not have overlaps between the hairpin and the junction, but one could argue that the current R2DT is more legible in the magenta region where the insertion is found.

Thank you for implementing this so quickly!

-----

Since we talked about constraint folding, I thought you mind find interesting this example R2DT drawing with RNArtist template and constrained folding (predicted basepairs are shown as dotted lines):

<img width="963" alt="Screenshot 2023-12-20 at 12 23 32" src="https://github.com/fjossinet/RNArtistCore/assets/432675/be20c2f0-8b02-4220-9d5a-cab5d63d1872">

and this is how RNArtist draws the same structure:

![rna_URS0000D690D1_12908](https://github.com/fjossinet/RNArtistCore/assets/432675/e4cce1f0-0e8a-4434-9fcc-4dd6c336ff9f)

R2DT tries very hard to maintain the original junction orientation and ends up with lots of overlaps. RNArtist completely redraws the junction, because it is not trying to force it into the template, but then the user would have to figure out which helix in the junction corresponds to which when comparing with a more compact RF01725. Drawing beautiful RNAs is hard!

**Comment by fjossinet** [comment]
I fixed the comma in the traveler output. Concerning the size of the area, you can define it as you need using [the properties width and height](https://github.com/fjossinet/RNArtistCore/blob/master/Changelog.md). The traveler DSL keyword is working exactly the same as png/svg keywords. 

[The update is available here](https://github.com/fjossinet/RNArtistCore/releases/tag/0.4.6-SNAPSHOT).

Let me know

**Comment by fjossinet** [comment]
> Hi Fabrice! It worked! 🎉
> 
> I have 2 small requests:
> 
> * Could you please change the decimal separator to `.` instead of `,` so that `958,87` becomes `958.87`?
> * Could you make the area smaller like 500x500 for consistency with existing R2DT templates?
> 
> Here is an R2DT visualisation for one of the longer instances of RF01725 (URS0000D690D1_12908):
> 
> <img alt="Screenshot 2023-12-20 at 12 04 25" width="1286" src="https://private-user-images.githubusercontent.com/432675/291885311-4d48796b-bd95-4099-9c51-d275f9a0e839.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNzc1MDQsIm5iZiI6MTcwMzA3NzIwNCwicGF0aCI6Ii80MzI2NzUvMjkxODg1MzExLTRkNDg3OTZiLWJkOTUtNDA5OS05YzUxLWQyNzVmOWEwZTgzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQxMzAwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzVhMmRkZTIyMzQ2MWU5Y2NmYzcyYWQxN2ViMmFlZjRlMmRiNTI4YTJlMTIxNDY2NjRjNzcyODg0YzYzNWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uuPb--rJTg1HzT5HbGfzexO0AAv3E188h0laiEg2iOk">
> and here is a default R2DT image based on R2R:
> 
> <img alt="Screenshot 2023-12-20 at 12 04 45" width="837" src="https://private-user-images.githubusercontent.com/432675/291885390-919cab33-613e-492e-9729-d6d287b1a985.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNzc1MDQsIm5iZiI6MTcwMzA3NzIwNCwicGF0aCI6Ii80MzI2NzUvMjkxODg1MzkwLTkxOWNhYjMzLTYxM2UtNDkyZS05NzI5LWQ2ZDI4N2IxYTk4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQxMzAwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ODFhNGJmNGJjY2E3NjRjMDY5YTIyY2IxZTUzNTAwODcxYmQ2NmRhYWUyMjgwOWZiMzI0MzMwMjJkNDRmYzk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HVapYJDkeUYfJ4t64F5H_SgX4S4G_G1kL6os0Ef4i3U">
> In this case I prefer the RNArtist layout because it does not have overlaps between the hairpin and the junction, but one could argue that the current R2DT is more legible in the magenta region where the insertion is found.
> 
> Thank you for implementing this so quickly!
> 
> Since we talked about constraint folding, I thought you mind find interesting this example R2DT drawing with RNArtist template and constrained folding (predicted basepairs are shown as dotted lines):
> 
> <img alt="Screenshot 2023-12-20 at 12 23 32" width="963" src="https://private-user-images.githubusercontent.com/432675/291889833-be20c2f0-8b02-4220-9d5a-cab5d63d1872.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNzc1MDQsIm5iZiI6MTcwMzA3NzIwNCwicGF0aCI6Ii80MzI2NzUvMjkxODg5ODMzLWJlMjBjMmYwLThiMDItNDIyMC05ZDVhLWNhYjVkNjNkMTg3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQxMzAwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2YyYTdjYTk0ZTNjYmU3YzU3ZTUyYmNkNTcwODU0NjhhMGM5NTIzNWM5Y2M2Zjk5ZDk4MTY5YmE3YWJkYzg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-soAN2JvNd3IfA_CMKB-ftDcLE4c7_5k2BBkXMRLLMo">
> and this is how RNArtist draws the same structure:
> 
> ![rna_URS0000D690D1_12908](https://private-user-images.githubusercontent.com/432675/291892268-e4cce1f0-0e8a-4434-9fcc-4dd6c336ff9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNzc1MDQsIm5iZiI6MTcwMzA3NzIwNCwicGF0aCI6Ii80MzI2NzUvMjkxODkyMjY4LWU0Y2NlMWYwLTBlOGEtNDQzNC05ZmNjLTRkZDZjMzM2ZmY5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMFQxMzAwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWNlYjIxMzVmM2RiYTQ5Y2MzZThiNDg0YTY0MDgzZjljODE2NjVmNzdkNjg1OGViYzIzNzUxZDA2ZGY4MjJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sJQ4BmyCFBJryDvoD3i6SWutx5LtP7rkT8H1Ibnr-i4)
> 
> R2DT tries very hard to maintain the original junction orientation and ends up with lots of overlaps. RNArtist completely redraws the junction, because it is not trying to force it into the template, but then the user would have to figure out which helix in the junction corresponds to which when comparing with a more compact RF01725. Drawing beautiful RNAs is hard!

Right! In RNArtist, you can also find this concept of template (I have to document it more and as I said, I had to inactivate some parts temporarily). It is working well with 2Ds derived from Rfam entries since I have a correspondence between the absolute positions in an RNA species and its absolute positions (columns) in the structural alignment. RNArtist will compute a non-overlapping layout for the consensus  2D and use it to plot the 2Ds for the species. If needed, I can use the graphical app RNArtist to change the layout for this consensus, or ask for more non-overlapping layouts to choose a better one (this feature will be available in the next release). I can also define a theme (colors, line widths). Once done, I ask RNArtist to apply this layout and theme to all the 2Ds for the species to easily compare them. 

Here is a simple example from one of my lecture. 

<img width="1430" alt="Capture d’écran 2023-12-20 à 14 25 33" src="https://github.com/fjossinet/RNArtistCore/assets/389452/208f29da-b68e-434a-b4e8-f32587b3173a">

When this part of my code will be reactivated, I will show you the result for a family with a more branched 2D.

**Comment by AntonPetrov** [comment]
> [The update is available here](https://github.com/fjossinet/RNArtistCore/releases/tag/0.4.6-SNAPSHOT).

Thank you so much! This is exactly what I needed. 

> Here is a simple example from one of my lecture.

This looks very neat!

> When this part of my code will be reactivated, I will show you the result for a family with a more branched 2D.

Please do! Maintaining the same orientation for related structures is so important for visualising RNAs.
